### ISSUE TITLE
GRC: Error in CL FFT block for GNURadio 3.8

### ISSUE THREAD

**Issue by lunar-mosiur** [ghostop14/gr-clenabled#9]
Problems in issue [#2158](https://github.com/gnuradio/gnuradio/issues/2158) is now existing in GR 3.8. I am observing this in CL-FFT blocks.

Fixes in [#1925](https://github.com/gnuradio/gnuradio/pull/1925) is already implemented in GR 3.8. However still the problem exists. Probably some modifications are necessary to this OOT module. 

![Selection_002](https://user-images.githubusercontent.com/9780881/74283277-3c3cdf00-4ce7-11ea-966b-af4d5b16344d.png)

**Comment by ghostop14** [comment]
I just pushed a fix so git pull to refresh your local repository and rebuild.  Should take care of it.
